force-app/main/default/objects/API_Key__c/fields/Api_link__c.field-meta.xml
<CustomField>
    <fullName>Api_link__c</fullName>
    <defaultValue>&quot;https://www.loqate.com/resources/support/apis/PhoneNumberValidation/Interactive/Validate/2.2/json3.ws?&quot;</defaultValue>
    <label>Api_link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Key__c/fields/Personal_Key__c.field-meta.xml
<CustomField>
    <fullName>Personal_Key__c</fullName>
    <defaultValue>&quot;PJ48-JE13-RG47-XX84&quot;</defaultValue>
    <label>Personal Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonDefaults__c/PersonDefaults__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>PersonDefaults</label>
</CustomObject>

force-app/main/default/objects/PersonDefaults__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Bulgaria&quot;</defaultValue>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/Phone_Validation_Result__c.object-meta.xml
<CustomObject>
    <label>Phone Validation Result</label>
    <nameField>
        <label>Phone_Validation_Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Validation Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APIName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/CountryPrefix__c.field-meta.xml
<CustomField>
    <fullName>CountryPrefix__c</fullName>
    <label>CountryPrefix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/IsValid__c.field-meta.xml
<CustomField>
    <fullName>IsValid__c</fullName>
    <label>IsValid</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NationalFormat__c.field-meta.xml
<CustomField>
    <fullName>NationalFormat__c</fullName>
    <label>NationalFormat</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkCode__c.field-meta.xml
<CustomField>
    <fullName>NetworkCode__c</fullName>
    <label>NetworkCode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkCountry__c.field-meta.xml
<CustomField>
    <fullName>NetworkCountry__c</fullName>
    <label>NetworkCountry</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkName__c.field-meta.xml
<CustomField>
    <fullName>NetworkName__c</fullName>
    <label>NetworkName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NumberType__c.field-meta.xml
<CustomField>
    <fullName>NumberType__c</fullName>
    <label>NumberType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipName>Phone_Validation_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>PhoneNumber</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/PhoneNumberToValidate__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumberToValidate__c</fullName>
    <label>PhoneNumberToValidate</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/RequestProcessed__c.field-meta.xml
<CustomField>
    <fullName>RequestProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RequestProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Validators/PhoneValidator.cls
public with sharing class PhoneValidator {
    @future(callout = true)
    public static void validate (ID personId, string personName, string personPhone, string validatedFieldName, string personCountry) {
        string country = '';
        
        if (!String.isBlank(personCountry)) {
            country = personCountry;
        }
        else country = PersonDefaults__c.getInstance(UserInfo.getUserId()).Country__c;

        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint(API_Key__c.getInstance(UserInfo.getUserId()).Api_link__c + 'Key=' + API_Key__c.getInstance(UserInfo.getUserId()).Personal_Key__c + '&Phone=' + personPhone + '&Country=' + country);
        HttpResponse httpResponse = http.send(req);
        Phone_Validation_Result__c pvr = new Phone_Validation_Result__c();
        pvr.Name = personName + ' ' + personPhone;
        pvr.Person__c = personId;
        if (httpResponse.getstatuscode() == 200){
            JSON2APEX obj = JSON2APEX.parse(httpResponse.getBody());
            if (obj.items[0].phoneNumber != null) {
                pvr.PhoneNumber__c = obj.items[0].phoneNumber;
                pvr.RequestProcessed__c = obj.items[0].requestProcessed;
                pvr.IsValid__c = obj.items[0].isValid;
                pvr.NetworkCode__c = obj.items[0].networkCode;
                pvr.NetworkName__c = obj.items[0].networkName;
                pvr.NetworkCountry__c = obj.items[0].networkCountry;
                pvr.NationalFormat__c = obj.items[0].nationalFormat;
                pvr.CountryPrefix__c = obj.items[0].countryPrefix;
                pvr.NumberType__c = obj.items[0].numberType;
                pvr.PhoneNumberToValidate__c = personPhone;
                pvr.APIName__c = validatedFieldName;
            } 
            else {
                pvr.Id__c = obj.items[0].error;
                pvr.Error__c = obj.items[0].description;
                pvr.Cause__c = obj.items[0].cause;
                pvr.Resolution__c = obj.items[0].resolution;
                pvr.PhoneNumberToValidate__c = personPhone;
                pvr.APIName__c = validatedFieldName;
            }
        }
        System.debug(pvr);
        Database.insert(pvr,false);
    }
}