force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/WorkPhone__c.field-meta.xml
<CustomField>
    <fullName>WorkPhone__c</fullName>
    <label>WorkPhone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/Phone_Validation_Result__c.object-meta.xml
<CustomObject>
    <label>Phone Validation Result</label>
    <nameField>
        <label>Phone_Validation_Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Validation Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/CountryPrefix__c.field-meta.xml
<CustomField>
    <fullName>CountryPrefix__c</fullName>
    <label>CountryPrefix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/IsValid__c.field-meta.xml
<CustomField>
    <fullName>IsValid__c</fullName>
    <label>IsValid</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NationalFormat__c.field-meta.xml
<CustomField>
    <fullName>NationalFormat__c</fullName>
    <label>NationalFormat</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkCode__c.field-meta.xml
<CustomField>
    <fullName>NetworkCode__c</fullName>
    <label>NetworkCode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkCountry__c.field-meta.xml
<CustomField>
    <fullName>NetworkCountry__c</fullName>
    <label>NetworkCountry</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkName__c.field-meta.xml
<CustomField>
    <fullName>NetworkName__c</fullName>
    <label>NetworkName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NumberType__c.field-meta.xml
<CustomField>
    <fullName>NumberType__c</fullName>
    <label>NumberType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipName>Phone_Validation_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>PhoneNumber</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/RequestProcessed__c.field-meta.xml
<CustomField>
    <fullName>RequestProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RequestProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Tests/PhoneValidationServiceTest.cls
@isTest
private class PhoneValidationServiceTest {
    @isTest static void PhoneValidationServiceTest_Insert_Phone_Is_Valid() {
        TriggerHelper.disabled = true;
        Person__c newPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', Phone__c = '+381654699581');
        string body = '{"Items":[{"PhoneNumber":"+381654699581","RequestProcessed":true,"IsValid":"Yes","NetworkCode":"03","NetworkName":"Telekom Srbija ad Beograd (mts)","NetworkCountry":"RS","NationalFormat":"065 4699581","CountryPrefix":381,"NumberType":"Mobile"}]}';
        HttpMockFactory mock = new HttpMockFactory(200, 'OK', body, new Map<String,String>());
        Test.setMock(HttpCalloutMock.class, mock);
      
        Test.startTest();
        insert newPerson;
        PersonValidationService.validatePhone( new Map<Id, SObject>{newPerson.Id => (SObject) newPerson}, null);
        Test.stopTest();
        List<Phone_Validation_Result__c> lastPVR = [select Id, PhoneNumber__c, RequestProcessed__c, IsValid__c, NetworkCode__c, NetworkName__c,NetworkCountry__c, NationalFormat__c, CountryPrefix__c, NumberType__c from Phone_Validation_Result__c ];
        System.debug(lastPVR);
        System.assertEquals(lastPVR[0].PhoneNumber__c, '+381654699581');
        System.assertEquals(lastPVR[0].RequestProcessed__c, true);
        System.assertEquals(lastPVR[0].IsValid__c, 'Yes');
        System.assertEquals(lastPVR[0].NetworkCode__c, '03');
        System.assertEquals(lastPVR[0].NetworkName__c, 'Telekom Srbija ad Beograd (mts)');
        System.assertEquals(lastPVR[0].NetworkCountry__c, 'RS');
        System.assertEquals(lastPVR[0].NationalFormat__c, '065 4699581');
        System.assertEquals(lastPVR[0].CountryPrefix__c, 381);
        System.assertEquals(lastPVR[0].NumberType__c, 'Mobile');
    }
    // @isTest static void PhoneValidationServiceTest_Insert_Phone_Null() {
    //     TriggerHelper.disabled = true;
    //     Person__c newPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', Phone__c = '');
    //     Test.startTest();
    //     PersonValidationService.validatePhone(newPerson, null);
    //     Test.stopTest();
    //     Integer count = [select count() from Phone_Validation_Result__c where Person__c = :newPerson.Id];
    
    //     System.assertEquals(count, 0);
    // }
    // @isTest static void PhoneValidationServiceTest_Insert_Phone_Error() {
    //     TriggerHelper.disabled = true;
    //     Person__c newPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', Phone__c = '+381654699581');
    //     string body = '{"Items":[{"Error":"1001","Description":"Number Required","Cause":"The phone numbers is required.","Resolution":"Please ensure that you supply a phone number and try again."}]}';
    //     HttpMockFactory mock = new HttpMockFactory(200, 'OK', body, new Map<String,String>());
    //     Test.setMock(HttpCalloutMock.class, mock);
    //     Test.startTest();
    //     PersonValidationService.validatePhone(newPerson, null);
    //     Test.stopTest();
    //     Phone_Validation_Result__c lastPVR = [select Id, Person__c, Id__c, Error__c, Cause__c, Resolution__c from Phone_Validation_Result__c order by CreatedDate desc limit 1];
    
    //     System.assertEquals(lastPVR.Person__c, newPerson.Id); 
    //     System.assertEquals(lastPVR.Id__c, 1001); 
    //     System.assertEquals(lastPVR.Error__c, 'Number Required');
    //     System.assertEquals(lastPVR.Cause__c, 'The phone numbers is required.');
    //     System.assertEquals(lastPVR.Resolution__c, 'Please ensure that you supply a phone number and try again.');

    // }
    // @isTest static void PhoneValidationServiceTest_Update_Phone_Is_Valid() {
    //     TriggerHelper.disabled = true;
    //     Person__c oldPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', Phone__c = '+381654699581');
    //     Person__c newPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', Phone__c = '+381654699582');
    //     string body = '{"Items":[{"PhoneNumber":"+381654699581","RequestProcessed":true,"IsValid":"Yes","NetworkCode":"03","NetworkName":"Telekom Srbija ad Beograd (mts)","NetworkCountry":"RS","NationalFormat":"065 4699581","CountryPrefix":381,"NumberType":"Mobile"}]}';
    //     HttpMockFactory mock = new HttpMockFactory(200, 'OK', body, new Map<String,String>());
    //     Test.setMock(HttpCalloutMock.class, mock);
    //     Test.startTest();
    //     PersonValidationService.validatePhone(newPerson, oldPerson);
    //     Test.stopTest();
    //     Phone_Validation_Result__c lastPVR = [select Id, PhoneNumber__c, RequestProcessed__c, IsValid__c, NetworkCode__c, NetworkName__c,NetworkCountry__c, NationalFormat__c, CountryPrefix__c, NumberType__c from Phone_Validation_Result__c order by CreatedDate desc limit 1];
        
    //     System.assertEquals(lastPVR.PhoneNumber__c, '+381654699581');
    //     System.assertEquals(lastPVR.RequestProcessed__c, true);
    //     System.assertEquals(lastPVR.IsValid__c, 'Yes');
    //     System.assertEquals(lastPVR.NetworkCode__c, '03');
    //     System.assertEquals(lastPVR.NetworkName__c, 'Telekom Srbija ad Beograd (mts)');
    //     System.assertEquals(lastPVR.NetworkCountry__c, 'RS');
    //     System.assertEquals(lastPVR.NationalFormat__c, '065 4699581');
    //     System.assertEquals(lastPVR.CountryPrefix__c, 381);
    //     System.assertEquals(lastPVR.NumberType__c, 'Mobile');
    // }
    // @isTest static void PhoneValidationServiceTest_Update_Workphone_Is_Valid() {
    //     TriggerHelper.disabled = true;
    //     Person__c oldPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', WorkPhone__c = '+381654699581');
    //     Person__c newPerson = new Person__c(Email__c = 'example@gmail.com', First_Name__c = 'name', Last_Name__c = 'lastname', WorkPhone__c = '+381654699582');
    //     string body = '{"Items":[{"PhoneNumber":"+381654699582","RequestProcessed":true,"IsValid":"Yes","NetworkCode":"03","NetworkName":"Telekom Srbija ad Beograd (mts)","NetworkCountry":"RS","NationalFormat":"065 4699582","CountryPrefix":381,"NumberType":"Mobile"}]}';
    //     HttpMockFactory mock = new HttpMockFactory(200, 'OK', body, new Map<String,String>());
    //     Test.setMock(HttpCalloutMock.class, mock);
    //     Test.startTest();
    //     PersonValidationService.validatePhone(newPerson, oldPerson);
    //     Test.stopTest();
    //     Phone_Validation_Result__c lastPVR = [select Id, PhoneNumber__c, RequestProcessed__c, IsValid__c, NetworkCode__c, NetworkName__c,NetworkCountry__c, NationalFormat__c, CountryPrefix__c, NumberType__c from Phone_Validation_Result__c order by CreatedDate desc limit 1];
        
    //     System.assertEquals(lastPVR.PhoneNumber__c, '+381654699581');
    //     System.assertEquals(lastPVR.RequestProcessed__c, true);
    //     System.assertEquals(lastPVR.IsValid__c, 'Yes');
    //     System.assertEquals(lastPVR.NetworkCode__c, '03');
    //     System.assertEquals(lastPVR.NetworkName__c, 'Telekom Srbija ad Beograd (mts)');
    //     System.assertEquals(lastPVR.NetworkCountry__c, 'RS');
    //     System.assertEquals(lastPVR.NationalFormat__c, '065 4699581');
    //     System.assertEquals(lastPVR.CountryPrefix__c, 381);
    //     System.assertEquals(lastPVR.NumberType__c, 'Mobile');
    // }
}