force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/WorkPhone__c.field-meta.xml
<CustomField>
    <fullName>WorkPhone__c</fullName>
    <label>WorkPhone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Services/PersonValidationService.cls
public with sharing class PersonValidationService {

    public static void validatePhone(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        Person__c newPerson = (Person__c) newItems.values()[0];
        Person__c oldPerson = null;

        if (oldItems != null) {
            oldPerson = (Person__c) oldItems.get(newPerson.Id);
        }
    
        if (!String.isBlank(newPerson.Phone__c)) {
            
            PhoneValidator.validate(newPerson.Id, newPerson.Name, newPerson.Phone__c, 'Phone__c', newPerson.Country__c);
            
        }

        // if (!String.isBlank(newPerson.WorkPhone__c)) {
        //     if (oldPerson == null || newPerson.WorkPhone__c != oldPerson.WorkPhone__c){
        //         PhoneValidator.validate(newPerson.Id, newPerson.Name, newPerson.WorkPhone__c, 'WorkPhone__c', newPerson.Country__c);
        //     }
        // }
        
    }

}